### PR TITLE
documented /info endpoint

### PR DESCRIPTION
**Pull request by anwilkie**
# Motivation and Context
I have been looking through rm-comms-template-service and documenting the API endpoints.

# What has changed
Modified API.md file to document /info endpoint.

# Links
[Trello card](https://trello.com/c/yIAqMY2Q)

### CODE REVIEW

**Review by insacuri — CHANGES_REQUESTED** [review]
You're missing the template and classification_type views and all their endpoints!

**Comment by anwilkie** [comment]
> You're missing the template and classification_type views and all their endpoints!

I checked the API.md file again and the endpoints for template and classification_type are there. In fact, they were already there when I started. The only potential problem is that those endpoints are formatted a little oddly in the documentation, since they use actual values in the URL instead of using the variable name (e.g. "GEOGRAPHY" instead of "classification_type"). If you'd like, I could change these to make them more consistent with the formatting of the API.md files in the other services.

**Review by insacuri — APPROVED** [review]
My bad sorry ^^ I hadn't noticed this was a continuation of a file that was already there.  No need to change anything else within the file, as long as it's consistent with itself (which it is with your change), then it's fine!

**Review by ryangrundy7 — APPROVED** [review]
LGTM 👍

**Pull request merged**
